# Generated by Django 3.1.4 on 2021-02-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['tournament', 'order_num']},
        ),
        migrations.AddField(
            model_name='match',
            name='match_slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_results',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tt_slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
