# Generated by Django 3.1.4 on 2021-01-25 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.PositiveIntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth'), (6, 'Sixth')], default=1)),
                ('tour_status', models.CharField(choices=[('crt', 'created'), ('prd', 'paired'), ('act', 'active'), ('fin', 'finished'), ('arch', 'archived')], default='crt', max_length=4)),
                ('tournament', models.ForeignKey(limit_choices_to={'status__in': ['ann', 'reg', 'act']}, on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tour',
            constraint=models.UniqueConstraint(fields=('order_num', 'tournament_id'), name='unique_tour'),
        ),
    ]
