# Generated by Django 3.1.4 on 2021-01-26 17:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournaments', '0002_auto_20210125_2054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerstats',
            options={'verbose_name_plural': 'Players Stats'},
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='tournaments.tournament'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opp1_gp', models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(12)])),
                ('opp2_gp', models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(12)])),
                ('opp1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opp1', to=settings.AUTH_USER_MODEL)),
                ('opp2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opp2', to=settings.AUTH_USER_MODEL)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tour')),
            ],
            options={
                'verbose_name_plural': 'matches',
            },
        ),
    ]
