# Generated by Django 3.1.4 on 2021-02-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tour_tour_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='tour_results',
            field=models.JSONField(default={'players': 'empty'}),
        ),
    ]
