# Generated by Django 3.1.4 on 2021-02-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_auto_20210201_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='tour_results',
            field=models.JSONField(null=True),
        ),
    ]
