# Generated by Django 3.1.4 on 2021-01-28 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournaments', '0004_auto_20210126_1843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerstats',
            options={'ordering': ['-tournament_points', '-difference', '-game_points'], 'verbose_name_plural': 'Players Stats'},
        ),
        migrations.AlterField(
            model_name='match',
            name='opp1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opp1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='opp2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opp2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tour'),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tournament',
            field=models.ForeignKey(limit_choices_to={'status__in': ['ann', 'reg', 'act']}, on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='tournaments.tournament'),
        ),
        migrations.AddConstraint(
            model_name='playerstats',
            constraint=models.UniqueConstraint(fields=('tournament', 'player'), name='unique_tournament_paleyr'),
        ),
    ]
