# Generated by Django 3.1.4 on 2021-02-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_auto_20210202_0805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['tournament', 'order_num']},
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_results',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
