# Generated by Django 3.1.4 on 2021-02-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_auto_20210202_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
