# Generated by Django 3.1.4 on 2021-02-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_match_match_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='tour_slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
