# Generated by Django 3.1.4 on 2021-02-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_tour_tour_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tt_slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
