# Generated by Django 3.1.4 on 2021-04-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tt_category',
            field=models.CharField(choices=[('nrt', 'narrative'), ('rtg', 'raiting')], default='rtg', max_length=4),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tt_type',
            field=models.CharField(choices=[('s', 'solo'), ('d', 'duo'), ('t', 'team')], default='s', max_length=4),
        ),
    ]
