# Generated by Django 3.1.4 on 2021-04-02 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_auto_20210402_1007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ['-start_date']},
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='status',
        ),
        migrations.AddField(
            model_name='tournament',
            name='tt_status',
            field=models.CharField(choices=[('ann', 'announce'), ('reg', 'registration'), ('creg', 'registration closed'), ('act', 'active'), ('fin', 'finished')], default='ann', max_length=4, verbose_name='Tournament Status'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tours_amount',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tt_category',
            field=models.CharField(choices=[('nrt', 'narrative'), ('rtg', 'raiting')], default='rtg', max_length=4, verbose_name='Tournament Category'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tt_slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tt_type',
            field=models.CharField(choices=[('s', 'solo'), ('d', 'duo'), ('t', 'team')], default='s', max_length=4, verbose_name='Tournament Type'),
        ),
    ]
