# Generated by Django 3.1.4 on 2021-04-02 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_auto_20210402_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
