# Generated by Django 3.1.4 on 2021-04-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_auto_20210402_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='table',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
