# Generated by Django 3.1.4 on 2021-04-10 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_match_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['table'], 'verbose_name_plural': 'matches'},
        ),
    ]
