# Generated by Django 3.1.4 on 2021-04-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_tournament_organizer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='organizer',
            new_name='superviser',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tt_category',
            field=models.CharField(choices=[('nrt', 'Нарративный'), ('rtg', 'Рейтинговый'), ('nyt', 'Новогодний')], default='rtg', max_length=4, verbose_name='Tournament Category'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tt_status',
            field=models.CharField(choices=[('ann', 'Анонс'), ('reg', 'Регистрация открыта'), ('creg', 'Регистрация закрыта'), ('act', 'Активный'), ('fin', 'Завершен')], default='ann', max_length=4, verbose_name='Tournament Status'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tt_type',
            field=models.CharField(choices=[('s', 'Одиночный'), ('d', 'Парный'), ('t', 'Командный')], default='s', max_length=4, verbose_name='Tournament Type'),
        ),
    ]
