# Generated by Django 3.1.4 on 2021-04-13 09:29

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_auto_20210410_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Дата проведения турнира', null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Время проведения турнира', verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='title',
            field=models.CharField(help_text='Название турнира', max_length=200, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tours_amount',
            field=models.PositiveIntegerField(default=3, help_text='Укажите количество туров в турнире - от 3 до 6', validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(6)], verbose_name='Кол-во туров'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tt_category',
            field=models.CharField(choices=[('nrt', 'Нарративный'), ('rtg', 'Рейтинговый'), ('nyt', 'Новогодний')], default='rtg', help_text='Выберите категорию турнира из списка', max_length=4, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tt_slug',
            field=models.SlugField(blank=True, help_text='Укажите слаг турнира', null=True, unique=True, verbose_name='Слаг турнира'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tt_status',
            field=models.CharField(choices=[('ann', 'Анонс'), ('reg', 'Регистрация открыта'), ('creg', 'Регистрация закрыта'), ('act', 'Активный'), ('fin', 'Завершен')], default='ann', help_text='Укажите статус турнира', max_length=4, verbose_name='Статус турнира'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tt_type',
            field=models.CharField(choices=[('s', 'Одиночный'), ('d', 'Парный'), ('t', 'Командный')], default='s', help_text='Выберите тип турнира из списка', max_length=4, verbose_name='Тип турнира'),
        ),
    ]
