# Generated by Django 3.1.4 on 2021-04-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_auto_20210413_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='table',
            field=models.PositiveIntegerField(default=666),
        ),
    ]
