# Generated by Django 3.1.4 on 2021-04-15 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0013_auto_20210415_1130'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='challenge',
            name='uniq_challenge',
        ),
        migrations.AlterField(
            model_name='challenge',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenges_tt', to='tournaments.tournament'),
        ),
        migrations.AddConstraint(
            model_name='challenge',
            constraint=models.UniqueConstraint(fields=('tournament', 'user', 'opponent'), name='uniq_challenge'),
        ),
    ]
