# Generated by Django 3.1.4 on 2021-04-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0014_auto_20210415_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='status',
            field=models.CharField(choices=[('acc', 'accept'), ('ref', 'refuse'), ('pen', 'pending')], default='pen', max_length=4),
        ),
    ]
