# Generated by Django 3.1.4 on 2021-04-09 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournaments', '0005_auto_20210402_1525'),
        ('players', '0002_auto_20210303_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstats',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tt_stats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registered_players', to='tournaments.tournament'),
        ),
    ]
