# Generated by Django 3.1.4 on 2021-04-13 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_auto_20210413_0929'),
        ('players', '0003_auto_20210409_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstats',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='tournaments.tournament'),
        ),
    ]
