# Generated by Django 3.1.4 on 2021-04-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_auto_20210413_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='proxy_bot',
            field=models.BooleanField(default=False),
        ),
    ]
